name: supply_chain_flutter_example
description: Example app for the supply_chain_flutter package.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  supply_chain: ^5.4.1
  supply_chain_flutter:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
