name: supply_chain_flutter
description: Flutter widgets connecting the supply_chain ecosystem to the UI.
version: 1.0.2
repository: https://github.com/ggsuite/supply_chain_flutter

environment:
  sdk: ">=3.12.2 <4.0.0"
  flutter: ">=3.44.4"

dependencies:
  flutter:
    sdk: flutter
  supply_chain: ^5.4.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
