// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/supply_chain_flutter_version_test.dart.
// coverage:ignore-file

/// The version of the `supply_chain_flutter` package.
const String supplyChainFlutterVersion = '1.2.0';
